services:
  # app:
  #   build: .
  #   env_file:
  #     - .env

  # langfuse-server:
  #   image: langfuse/langfuse:2
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
  #     - NEXTAUTH_URL=http://localhost:3000

  db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    restart: unless-stopped

  migrations:
    image: 'book_bot'
    restart: 'no'
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["alembic", "upgrade", "heads"]

volumes:
  database_data:
  pgadmin: